name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install

  quality:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: bun lint:ci

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: bun run build
